[package]
name = "mochios-developer-ca"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base64 = "0.22"
ed25519-dalek = { version = "2", features = ["rand_core", "pkcs8"] }
getrandom = { version = "0.4", features = ["wasm_js"] }
mochios-certificate = { git = "https://github.com/mochiOS/syscalls", rev = "ee6be939de4635824df7f50858d66391dd6ead41" }
mochios-developer-ca-trust = { path = "crates/trust" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
subtle = "2"
uuid = { version = "1", features = ["v7", "serde", "rng-getrandom"] }
worker = { version = "0.8.4", features = ["d1"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
