name = "mochios-developer-ca"
main = "build/worker/shim.mjs"
compatibility_date = "2026-07-26"

[build]
command = "worker-build --release --no-panic-recovery"

[vars]
ACCOUNTS_BASE_URL = "https://accounts.mochios.org"
CERTIFICATE_TTL_SECONDS = "31536000"

[triggers]
crons = ["*/15 * * * *"]

[[routes]]
pattern = "ca.mochios.org"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "mochios-developer-ca"
database_id = "4cea84e3-6120-4a62-983a-8af796a899ea"
migrations_dir = "migrations"
